services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs-app:
    image: chillteacher-v2-app:latest
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - '80:80' # HTTP
      - '443:443' # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro # Mount the Caddyfile
      - caddy_data:/data # Persistent storage for Caddy (e.g., SSL certs)
    depends_on:
      - nextjs-app

volumes:
  db_data:
  caddy_data:
